#ifndef ERRORCODES_HPP
#define ERRORCODES_HPP

// CIMContentHandler
#define CIMPARSER_OBJECT_STACK_ERROR 1
#define CIMPARSER_TAG_STACK_ERROR 2
#define CIMPARSER_OBJECT_CONTAINER_NOT_SET 3
#define CIMPARSER_RDF_MAP_NOT_SET 4
#define CIMPARSER_OBJECT_WITHOUT_RDF_ID 5

#endif // ERRORCODES_HPP
