name: Documentation

on:
  pull_request:
  push:
    branches: [master]

env:
  BUILD_TYPE: Release

jobs:
  build-doc-artifacts:
    name: Build and Upload doc Artifacts
    runs-on: ubuntu-latest

    strategy:
      matrix:
        schema:
        - CGMES_2.4.13_18DEC2013
        - CGMES_2.4.15_16FEB2016
        - CGMES_2.4.15_27JAN2020
        - CGMES_3.0.0

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Install Dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libboost-filesystem-dev libboost-system-dev libboost-test-dev doxygen graphviz

    - name: Configure CMake
      run: >
          cmake -B ${{github.workspace}}/build_${{matrix.schema}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DUSE_CIM_VERSION=${{matrix.schema}}

    - name: Build doc
      run: cmake --build ${{github.workspace}}/build_${{matrix.schema}} --parallel 4 --target doc

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: doc_${{matrix.schema}}
        path: ${{github.workspace}}/build_${{matrix.schema}}/doc/html

  build-gh-pages-artifact:
    name: Build and Upload Artifact github-pages
    needs: build-doc-artifacts
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      CIM: CGMES_3.0.0
    steps:
    - name: Download
      uses: actions/download-artifact@v8
    - name: Copy
      shell: bash
      run: |
          mkdir -p ./copy_files/docs
          cp -r ./doc_${{env.CIM}} ./copy_files/docs/${{env.CIM}}
          echo "<html><head><meta http-equiv='refresh' content='0; url=${{env.CIM}}/index.html' /></head></html>" >./copy_files/docs/index.html
    - name: Upload Artifact github-pages
      uses: actions/upload-pages-artifact@v5
      with:
        path: ./copy_files/docs

  deploy-gh-pages:
    name: Deploy github-pages
    needs: build-gh-pages-artifact
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
