name: Build & Test on Linux

on: [push, pull_request]

env:
  BUILD_TYPE: Release

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        schema:
        - CGMES_2.4.13_18DEC2013
        - CGMES_2.4.15_16FEB2016
        - CGMES_2.4.15_27JAN2020
        - CGMES_3.0.0

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Install Dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libboost-filesystem-dev libboost-system-dev libboost-test-dev

    - name: Configure CMake
      run: >
          cmake -B ${{github.workspace}}/build_${{matrix.schema}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DUSE_CIM_VERSION=${{matrix.schema}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build_${{matrix.schema}} --parallel 4

    - name: Test
      working-directory: ${{github.workspace}}/build_${{matrix.schema}}
      run: ctest --output-on-failure --output-junit test-results.xml

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: ${{ !cancelled() }}
      with:
        files: "${{github.workspace}}/build_${{matrix.schema}}/test-results.xml"
        check_name: "Test Results (${{matrix.schema}})"
