name: Release Packages
on:
  push:
    tags: ['release/v*']
jobs:
  package:
    runs-on: ubuntu-latest
    name: Build Packages
    strategy:
      matrix:
        schema:
        - CGMES_2.4.13_18DEC2013
        - CGMES_2.4.15_16FEB2016
        - CGMES_2.4.15_27JAN2020
        - CGMES_3.0.0
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7
    - name: Build Packages
      uses: ./package/
      env:
        USE_CIM_VERSION: ${{matrix.schema}}
    - name: Upload RPM Package
      uses: actions/upload-artifact@v7
      with:
        name: rpm_${{matrix.schema}}
        path: ${{ github.workspace }}/build/*.rpm
    - name: Upload DEB Package
      uses: actions/upload-artifact@v7
      with:
        name: deb_${{matrix.schema}}
        path: ${{ github.workspace }}/build/*.deb
  release:
    needs: package
    name: Release Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: GetArtifact
      uses: actions/download-artifact@v8
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        files: |
          */*.rpm
          */*.deb
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
